### ISSUE TITLE
[Issue] Not working for Fabric 1.19.2

### ISSUE THREAD

**Issue by Nekkok** [motivational-dragon/Potion-Blender#1]
Hi! I really love the idea of this mod, however I can't fill the brewing cauldron with any potion :(
I don't know if there's some compatibility issue around it, I have a _really_ long list of mods installed and some them maybe causing this issue. 

I'm sending you the log. Thank you! 
[latest.log](https://github.com/motivational-dragon/Potion-Blender/files/10680606/latest.log)

**Comment by motivational-dragon** [comment]
Weird, does the item float on the cauldron or is it picked up by the cauldron but nothing appear? I know sodium sometime cause rendering issues.

Anyways since i am missing quite a bit of information here could you please recreate the issue using the template i just added?

Thank in advance
