### ISSUE TITLE
[Bug] Cauldron Block Doesn't follow campfire lit BlockState

### ISSUE THREAD

**Issue by guivnf** [motivational-dragon/Potion-Blender#11]
https://github.com/motivational-dragon/Potion-Blender/assets/77132244/dd8b6e55-01e9-4d3e-8451-72ee22541cdc

So as you can see in the video, the Blockstate of the placed campfire is ``campfire{BlockStateTag:{lit:"false"}}`` Though when placing the cauldron on top of it, it changes the campfire itself to be lit, which's a bit odd and in my opinion it breaks the whole imersion of it. I know that the cauldron block doesn't have an unlit state or anything, but it'd be nice to have it, specially because it'd complement vanilla minecraft quite well and give a seameless feeling to it.

**Comment by motivational-dragon** [comment]
I can add an unlit state that copies the campfire state; this is easily done. 

The trickier part is handling the list of items that can light/douse the campfire.

In vanilla MC, the items call a static method on the campfire, which makes inheriting from the campfire hard (it also has a bunch of extra block properties, too). I guess I will have to hardcode a list of items and add them to the config.

**Comment by motivational-dragon** [comment]
![2024-04-28_11 55 43](https://github.com/motivational-dragon/Potion-Blender/assets/116593274/03440160-087e-408a-92a7-36754175aa63)

Scheduled for next release. I might have overdone it with the soulfire cauldron.
