### ISSUE TITLE
Effect Stacking Results in Negative Duration

### ISSUE THREAD

**Issue by WaitingLix** [motivational-dragon/Potion-Blender#16]
fabric,1.20.1
mod version:3.1.1

When adding the same effect to a potion multiple times, the resulting duration overflows and becomes a negative value.

- Merging three effects with a duration of 9600 (8min)results in a duration of -2147464449.
- Merging three effects with a duration of 3600 (3min)results in a duration of -2147476449.
- Merging two effects with a duration of 3600 (3min)results in a duration of -2147470049.

**Comment by motivational-dragon** [comment]
Should be fixed in the new version i uploaded (3.1.1.1 for mc 1.20.1)
