### ISSUE TITLE
Add a levitation potion to the custom cauldron recipies

### ISSUE THREAD

**Issue by NalterSuspect** [motivational-dragon/Potion-Blender#17]
Hi. I'm currently using the potion-blender mod (1.20.1) and I was wondering if it's possible to add a levitation potion to the custom cauldron recipes.

The potion look like this in command line:
/give @p minecraft:potion{display:{Name:"{\"text\":\"Potion of Levitation\",\"italic\":\"false\"}"},CustomPotionEffects:[{Id:25,Amplifier:30,Duration:50}],Potion:"minecraft:water",CustomPotionColor:7697781}

Thank you for create this mod is so fun!

**Comment by motivational-dragon** [comment]
Adding custom recipe is done trough datapack (you can look up a tutorial like the one for [create ](https://github.com/Creators-of-Create/Create/wiki/Custom-Recipes)it work basically the same). I also put a few recipes examples on the [wiki](https://github.com/motivational-dragon/Potion-Blender/wiki/Recipes).

However, prior to 1.2O.5 it was impossible to add NBT tag to recipe output in datapack and therefore impossible to add potion effects. You can either use a mod to add NBT tag in recipe or update minecraft.

Hope i helped you, feel free to ask if you have more questions :)

**Comment by NalterSuspect** [comment]
I installed the NBT recipes mod. Works perfectly now.

Thanks for the help!
