### ISSUE TITLE
Can't blend more potion even though changing the config

### ISSUE THREAD

**Issue by Ocpkayp6662** [motivational-dragon/Potion-Blender#18]
I'm using 1.20.1 Forge 3.1.1.1 Version.

I changed the inv size to 9 but I can't combine 8 potions (8 potions + Finishing ingredient = 9), They add together but when I add the finishing ingredient It just gets added and doesn't brew.

I don't know if it's hard coded into the mod that if it's only 3 potions or I am doing something wrong, I would like to mix and blend as many as potions if it is possible.

**Comment by motivational-dragon** [comment]
Changing the inv size does not modify recipies. It's main goal was allowing player who wanted to add complex custom recipe to do so.

So in your case you need to add a custom recipe for each combination. i made a small tool to enumerate recipe at https://motivational-dragon.github.io/potion-blender-recipe-enumerator/recipe.html

I know this is suboptimal but the reason recipies are not dynamically generated is to allow player to override them. Maybe what i will do is add more default recipe to allow a bit of room.

Hope i still helped you!

**Comment by Ocpkayp6662** [comment]
I was kinda hoping for the to mod let us combine any potion even the modded ones without a limit or us making a recipe for it.
I also suck at making the recipe thing too, Well I guess I'll wait for future updates then.
Thanks.

**Comment by motivational-dragon** [comment]
Fixed in latest release, should work with up to 10 potions +1 ingredients
