### ISSUE TITLE
[Issue]Potion Blender breaks all uncombined lingering potions

### ISSUE THREAD

**Issue by SirSirom** [motivational-dragon/Potion-Blender#2]
None of them linger , they dissapear instantly simmilarly to splash potions

first found on 1.19.2 - 1.0.1,
tested on 1.19.3 - 1.0.2,
still persists

personal request: port fix to 1.19.3 and 1.19.2

**Comment by motivational-dragon** [comment]
Fixed in 1.0.3 version. Currently only available for 1.19.3 but i will port it to 1.19.2 as well.
