### ISSUE TITLE
Game breaking bug ATM9

### ISSUE THREAD

**Issue by skyx700** [motivational-dragon/Potion-Blender#5]
Looks like potion blender breaks some other mods:
Original thread: https://github.com/P3pp3rF1y/Reliquary/issues/645

"When right clicking a bucket of water into the apothecary cauldron it crashes the client game (not the server) and it breaks the chunk at and below the cauldron up to 16 blocks (probably isolated to the chunk section based on chunk viewing) causing existing and new blocks placed to not appear. Restarting doesn't fix the chunk only restoring a backup. The current modpack installed is All the Mods 9 pack version 0.0.65.

Context probably isn't relevant but I was trying to figure out why potion mixing wasn't working with certain mods, and trying to add water to cauldron's was part of the testing."

![chunkbroken3](https://github.com/motivational-dragon/Potion-Blender/assets/76631175/fc86ee77-105f-4e64-8a48-efa31a29d56a)
![chunk broken1](https://github.com/motivational-dragon/Potion-Blender/assets/76631175/2b101f7d-5947-46a9-b6c1-46a88337be3e)
![chunk broken2](https://github.com/motivational-dragon/Potion-Blender/assets/76631175/3d788798-c9d6-42b7-a7a1-8e71554c1e1b)

Crash Logs:
[crash-2023-09-07_18.32.55-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/12554308/crash-2023-09-07_18.32.55-client.txt)
[crash-2023-09-07_17.58.53-client.txt](https://github.com/P3pp3rF1y/Reliquary/files/12554309/crash-2023-09-07_17.58.53-client.txt)

**Comment by motivational-dragon** [comment]
So, to make sure I understand correctly. When placing Reliquary Apothecary Cauldron, you right-clicked with a water bucket to fill the cauldron, and your client crashed. Is that right?
I cannot reproduce this issue. Can you reproduce this bug on a solo world? Then, If it still crashes, can you try without rendering mod like sodium/oculus?

**Comment by skyx700** [comment]
Uninstalled oculus and rubidium. no crashes. Seems I'm having all the game-crashing server breaking bugs with rubidium/oculus these last 2 days.
