### ISSUE TITLE
[Enhancement] Add recipe data type for Potion Blender

### ISSUE THREAD

**Issue by guivnf** [motivational-dragon/Potion-Blender#7]
So basically one of the biggest issues rn is how recipes are all hard coded and based of of the ones in vanilla, i think this is a very impractical way of doing this as it leaves almost 0 ground for modpack makers and users in general to customize and create their own recipes for custom potions added by other mods. 

My idea would be to handle potion recipes for potion blender simmilarly to how recipes for new crating stations like the "Crafting Table" are handled. 

See below
```json
{
    "type": "minecraft:crafting_shaped",
    "pattern": [
        "###",
        " / ",
        " / "
    ],
    "key": {
        "#": {
            "item": "minecraft:cobblestone"
        },
        "/": {
            "item": "minecraft:stick"
        }
    },
    "result": {
        "item": "minecraft:stone_pickaxe",
        "count": 1
    }
}
```
*Recipe for a stone pickaxe*

As you can see this could kinda be applied to potion blender, but i doubt it'd work the same way as it doesn't have it's own custom GUI, so maybe make it so instead of dropping potions you right click them on the cauldron, and you can customize the specific order you need to add them to the cauldron within the recipe data.  Would also be nice to be able to set a different time for each recipe in the recipe data json.

This change would also allow people to add recipes that are not related at all with potions, like for example, if i wanted to make it so you get a specific item after right clicking them on the cauldron... (i.e 1° right click "Leather" on the cauldron, 2° right click honeycomb, wait X ammount of time specified in the recipe data, and get a new custom item "Tanned Leather")

I'm not sure if this is where you plan to take the mod, but i think this would also cut your work in relation to other mods by 90% as you'd be giving the tools to the community to make your mod more compatible with others. 

Here's an example of what it could look like 

```json
{
    "type": "potionblender:cauldron",
     "duration":120, //In ticks or seconds, whatever is easier
    "pattern": [
        "#",
        "/"
    ],
    "key": {
        "#": {
            "item": "minecraft:leather"
        },
        "/": {
            "item": "minecraft:honeycomb"
        }
    },
    "result": {
        "item": "kubejs:tanned_leather",
        "count": 1
    }
}
```

Thats it :)
(Also i know it's easier said than done, but that'd be my solution for most of the problems i found when using this mod, might fork this and make these changes in the future, but yeah idk)

**Comment by motivational-dragon** [comment]
You are not the first to ask me for a way to change the config, and I agree that a proper way to configure the mod is needed.

What vanilla minecraft does is declare a recipe type with whatever your block needs, then serialize it into JSON. It also handles the recipe synchronization between the client and server and allows easy integration with JEI.

However, this means you must know every recipe you want in advance. Since the mod needs to work for every combination of potions, there are infinite recipes.

A workaround could be to declare a template recipe on which to apply the potion merging rules, and there would, by default, only be 3 template for each potion type. This could work like this

``` json
{
 "type" : "potionblender:potion_blending",
  "brewingTime" : 7,
  "MergePotion": true,
  "ingredients": [
    {
      "item": "minecraft:potion" // all normal potion in mc are in fact 1 item! so this work like a wildcard
    },
    {
      "item": "minecraft:potion"
    }
    {
      "item": "minecraft:potion"
    }
  ],
  "output" : {
    "item" : "minecraft:potion"
    "count" : 1 // i did not think to add the count, but this could be pretty cool
  }
}
```

Same for lingering potion, you get the idea...

``` json
{
 "type" : "potionblender:potion_blending",
  "brewingTime" : 7,
  "MergePotion": true,
  "ingredients": [
    {
      "item": "minecraft:splash_potion" 
    },
    {
      "item": "minecraft:splash_potion"
    }
    {
      "item": "minecraft:splash_potion"
    }
  ],
  "output" : {
    "item" : "minecraft:potion"
    "count" : 1 // i did not think to add the count, but this could be pretty cool
  }
}
```

you could then adapt your recipe like that
``` json
"type" : "potionblender:potion_blending",
  "brewingTime" : 7,
  "MergePotion": false,
  //maybe also color since this is otherwise calculated from potions colors?
  "ingredients": [
    {
         "item": "minecraft:leather"
    },
    {
      "item": "minecraft:honeycomb"
    }
  ],
    "output": {
        "item": "kubejs:tanned_leather",
        "count": 1
    }
```

Notes: it uses an array to give a crafting order, for instance the order in which the items are dropped into the cauldron

I looked into changing that a while ago on a [branch](https://github.com/motivational-dragon/Potion-Blender/tree/test-custom-brewing-recipe-1.20.2 ) but did not complete it because I am not sure what is best for the user and don't have as much time for modding as before (modding in a nutshell). Anyway, let me know if you have a better idea or any improvement (like missing config parameters).

**Comment by guivnf** [comment]
> Notes: it uses an array to give a crafting order, for instance the order in which the items are dropped into the cauldron
> 
> I looked into changing that a while ago on a [branch](https://github.com/motivational-dragon/Potion-Blender/tree/test-custom-brewing-recipe-1.20.2) but did not complete it because I am not sure what is best for the user and don't have as much time for modding as before (modding in a nutshell). Anyway, let me know if you have a better idea or any improvement (like missing config parameters).

I think you are right, arrays would be way better for this indeed, well the way you showed me looks perfect in my eyes. You basically covered everything i said, brewing time, output count, and allowing different items from being brewed. I think instead of declaring colors, you could allow us to declare a resouceLocation for maybe a custom texture or something, so people can display custom animated textures for each different recipe yk, that's just an idea tho, colors is also a great thing, whatever really :) 

If you need a can help you out in documenting it here on GitHub, just gotta open the wiki tab

**Comment by motivational-dragon** [comment]
I enabled the wiki and created the first page. I hope to fill it overtime. Any help is very much welcomed.

I don't know much about git wiki. I think you will have to clone it locally and then push it to the master branch.

**Comment by guivnf** [comment]
> I enabled the wiki and created the first page. I hope to fill it overtime. Any help is very much welcomed.
> 
> I don't know much about git wiki. I think you will have to clone it locally and then push it to the master branch.

Nice, but mind that i'm unable to edit it without being elavated to a contributor. I've never really clonned a wiki before but i'll see how it goes. You might need to make some changes because i'm unsure as to what you'll be doing nor do i know the exact recipe structure you'll be going for. But i'll try my best :)

**Comment by motivational-dragon** [comment]
> Nice, but mind that i'm unable to edit it without being elavated to a contributor

It sucks that GitHub Wiki does not support pull requests. Come on, GitHub. If you cannot push your change to the wiki, I will temporarily make editing the wiki public. Still, I'm not too fond of the idea of anything editing the wiki without any proofreading.

> You might need to make some changes because i'm unsure as to what you'll be doing nor do i know the exact recipe structure you'll be going for. But i'll try my best :)

Don't worry. If anything is wrong, I will correct it. It is already very cool of you to use some of your time to write the doc. I immensely appreciate it 👍 .

So let's write a bit of spec:

``` json

"type" : "potionblender:potion_blending",
  "brewingTime" : 7, // in tick, between 0 and  Integer.MAX_VALUE
  "mergePotion": false, // true if the potions merging rules should apply. Optional field
  "color": 0xFFFFFFFF //using textures would be cool, but for the time being the goal is having recipes working with simple colors. Using image requires re-coding the rendering logic.
  
  "orderedRecipe":true // if true the item need to match the order given by the recipe
  "effectStackingDecayRate" : 2.0 // See last merging rule, optional and default to 2 if needed. Positive floating point number

  // an array contening the ingredients, max limit is currently arbitrary at 8, could be tweaked 
  "ingredients": [
    {
         "item": "minecraft:leather"
    },
    {
      "item": "minecraft:honeycomb"
    }
  ],
    "output": {
        "item": "kubejs:tanned_leather",
        "count": 1
    }
```


As for merging rules (they could also become configurable in the future, maybe with kube.js) : 
-  Two potion effects can stack if they have the same effect and amplifier (different amplifier and up overriding the weaker one)
-  Identical instant potion does not stack, but you can add different tiers such as instant heal 1 and 2 (it gets broken real quick otherwise)
-  Stacking multiple effect result in an inverse proportional gain; ie, First added potion has 1/2 the duration, 2nd 1/3, 3rd 1/4. Set to 1 to disable (and break the game)

**Comment by happy44300** [comment]
I added a configurable implemented a recipe type with JEI integration (and even some graphical overhaul). Here is a preview [Potion-Blender-1.20.2-FABRIC-SNAPSHOT-3.0.0-RC1.jar.zip](https://github.com/motivational-dragon/Potion-Blender/files/14894323/Potion-Blender-1.20.2-FABRIC-SNAPSHOT-3.0.0-RC1.jar.zip)


There are some additional recipes used for testing like for instance

``` json
{
  "type" : "potionblender:potion_blending",
  "brewingTime" : 140,
  "usePotionMergingRules": false,
  "color": 29999680,
  "isOrdered": true,
  "ingredients": [
    {
      "item": "minecraft:melon_slice"
    },
    {
      "item": "minecraft:gold_nugget"
    }
  ],
  "output" : {
    "item" : "minecraft:glistering_melon_slice",
    "count" : 1
  }
}
```
or 

``` json
{
  "type" : "potionblender:potion_blending",
  "brewingTime" : 140,
  "usePotionMergingRules": false,

  "color": 16711680,
  "isOrdered": false,
  "ingredients": [
    {
      "item": "minecraft:apple"
    },
    {
      "item": "minecraft:gold_nugget"
    }
  ],
  "output" : {
    "item" : "minecraft:golden_apple",
    "count" : 1
  }
}

```

I also wanted to know if you ended writing any documentation? If not i am marking this issues as completed as all i need to do now is testing before the newt release

**Comment by guivnf** [comment]
> Hello again, I added a configurable implemented a recipe type with JEI integration (and even some graphical overhaul). Here is a preview [Potion-Blender-1.20.2-FABRIC-SNAPSHOT-3.0.0-RC1.jar.zip](https://github.com/motivational-dragon/Potion-Blender/files/14894323/Potion-Blender-1.20.2-FABRIC-SNAPSHOT-3.0.0-RC1.jar.zip)
> 
> There are some additional recipes used for testing like for instance
> 
> ```json
> {
>   "type" : "potionblender:potion_blending",
>   "brewingTime" : 140,
>   "usePotionMergingRules": false,
>   "color": 29999680,
>   "isOrdered": true,
>   "ingredients": [
>     {
>       "item": "minecraft:melon_slice"
>     },
>     {
>       "item": "minecraft:gold_nugget"
>     }
>   ],
>   "output" : {
>     "item" : "minecraft:glistering_melon_slice",
>     "count" : 1
>   }
> }
> ```
> 
> or
> 
> ```json
> {
>   "type" : "potionblender:potion_blending",
>   "brewingTime" : 140,
>   "usePotionMergingRules": false,
> 
>   "color": 16711680,
>   "isOrdered": false,
>   "ingredients": [
>     {
>       "item": "minecraft:apple"
>     },
>     {
>       "item": "minecraft:gold_nugget"
>     }
>   ],
>   "output" : {
>     "item" : "minecraft:golden_apple",
>     "count" : 1
>   }
> }
> ```
> 
> I also wanted to know if you ended writing any documentation? If not i am marking this issues as completed as all i need to do now is testing before the newt release

I haven't written any documentation on it yet. I'm unsure of what the mod author is working on at the moment as i was waiting for his answer on the wiki issue, because i'm simply unable to contribute to it without being a verified contributor. I could try writting an arkdown page and just attaching it here, but idk if the author would agree on it. Looking from his past commits referencing this issue, he might still be up to working on it.

Maybe try attaching you fork link here so he can use your code as reference for the update, idk. In any case, i also don't really use fabric at all + i'm unsure if there's any notable structure changes to the main recipe structure here discussed.

**Comment by motivational-dragon** [comment]
@happy44300 is a friend who helped me directly on the project rather than on GitHub. I should have posted directly to avoid confusion. I also just realized I forgot to link the branch I was working on, so my commits from last month are not showing up 🤦 . I apologize for the lack of communication here. To clarify, I approved the early fabric snapshot from @happy44300 , which was built from [my branch](https://github.com/motivational-dragon/Potion-Blender/tree/test-custom-brewing-recipe-1.20.2). If you don't use fabric, you can always wait for the forge port. However, this might take a while since I want to ensure the mod is stable with the new features before porting to forge/neoforge.

I cannot give you access to the wiki only. The collaborator role would give you the rights to the entire repo. So, instead, I am making the wiki public. I hope I clarified things enough, your help is still very much welcome 👍

**Comment by guivnf** [comment]
> @happy44300 is a friend who helped me directly on the project rather than on GitHub. I should have posted directly to avoid confusion. I also just realized I forgot to link the branch I was working on, so my commits from last month are not showing up 🤦 . I apologize for the lack of communication here. To clarify, I approved the early fabric snapshot from @happy44300 , which was built from [my branch](https://github.com/motivational-dragon/Potion-Blender/tree/test-custom-brewing-recipe-1.20.2). If you don't use fabric, you can always wait for the forge port. However, this might take a while since I want to ensure the mod is stable with the new features before porting to forge/neoforge.
> 
> 
> 
> I cannot give you access to the wiki only. The collaborator role would give you the rights to the entire repo. So, instead, I am making the wiki public. I hope I clarified things enough, your help is still very much welcome 👍 

Ok so I think the wiki is in a really great state and ready to be used tho I'm not sure if it's up to your standards so make sure to check if there's not typos or missing information

**Comment by motivational-dragon** [comment]
Thank you very much for the help. I hope to keep completing the wiki with each update but for now this is good. I will make sure to credit you in the next release.

**Comment by guivnf** [comment]
> Thank you very much for the help. I hope to keep completing the wiki with each update but for now this is good. I will make sure to credit you in the next release.

Lmk once you get around to porting it to forge 1.20.1 or if you need help with it

**Comment by guivnf** [comment]
> Thank you very much for the help. I hope to keep completing the wiki with each update but for now this is good. I will make sure to credit you in the next release.

Oh btw, if you can please make sure to lock the wiki to avoid it from being deleted or changed by unwanted members xD

**Comment by motivational-dragon** [comment]
> Lmk once you get around to porting it to forge 1.20.1 or if you need help with it

1.20.1 forge is the version most used in mod packs such as ATM9. I would rather not break modpacks used by millions of users. I will wait at least 1 month after the first release for feedback before considering it stable. I may release a beta version earlier tho idk. If you want to be alerted when new versions are released, you can always subscribe on curseforge or Modrinth (i am planning to publish on Modrinth again). 

>Oh btw, if you can please make sure to lock the wiki to avoid it from being deleted or changed by unwanted members xD

OOPSIE: Thank you for reminding me 👍
