### ISSUE TITLE
Outdated version on Modrinth

### ISSUE THREAD

**Issue by SanguardMC** [motivational-dragon/Potion-Blender#8]
The last version that's available on Modrinth is 1.1.0 for 1.20.1 (both forge and fabric), while on Curseforge the version 2.0.0 can be found, and even for 1.20.4
I'd like to know if the updated version will be available on Modrinth at some point, or I have no choice but to use Curseforge (Just asking for curiosity)

**Comment by motivational-dragon** [comment]
I like the idea of CurseForge not being the only place distributing my mod. However, few users were using Modrinth, so I stopped publishing on both sites (which may be why Nodoby is downloading it from Modrinth, lol).

I can update the mod on Modrinth for now if you want, but I can't guarantee updates. 

The best solution is to have a pipeline for publishing on both sites. However, this would take precious time away from maintaining the mod.

**Comment by motivational-dragon** [comment]
Updated versions on modrinth to the latest available versions
